### PR TITLE
Theme checks grouping improvements

### LINKED ISSUE #215: Introduce new groupings for check results
### Objective
Theme fatal errors, errors, warnings, and recommendations should be grouped separately. Eventually, messages should be grouped by (1) message level and then (2) by file.

### Grouping design
```
Fatal errors
Must be fixed to be able to activate theme.

- [file 1]
  - [fatal error 1.1]
  - [fatal error 1.2]
  - …
- [file 2]
  - [fatal error 2.1]
  - [fatal error 2.2]
  - …
- …

Errors
Highly recommended to fix, functionality could be restricted.

- [file 1]
  - [error 1.1]
  - [error 1.2]
  - …
- [file 2]
  - [error 2.1]
  - [error 2.2]
  - …
- …

Warnings

- [file 1]
  - [warning 1.1]
  - [warning 1.2]
  - …
- [file 2]
  - [warning 2.1]
  - [warning 2.2]
  - …
- …

Recommendations

- [file 1]
  - [recommendation 1.1]
  - [recommendation 1.2]
  - …
- [file 2]
  - [recommendation 2.1]
  - [recommendation 2.2]
  - …
- …
```

Todo:
- [ ] fatal error/error grouping
- [ ] investigate `skipped` group usage
- [ ] add ability to group by file

### PR DESCRIPTION
**Pull request by gargol**
closes #215

### CODE REVIEW

**Comment by peterzimon** [comment]
@gargol looks awesome, I think there are just two minor refinements:
1. let's have an empty row before `Checking theme compatibility...` (otherwise it's getting too much crammed with the command)
2. let's have three dots after `Checking theme compatibility...` (now it's just 2)

**Comment by gargol** [comment]
@peterzimon the tweak above landed in master with a680d7875942868c557ce39d8d3ed9ca01f6ccd1 . They were not too related to this changeset, so pushed them right away :+1:

**Comment by gargol** [comment]
These will need an additional review of how new 'fatal' group is used in Ghost-Admin and gscan web client. Will be done once other priorities are cleared.

**Comment by gargol** [comment]
To be revived once this issue becomes a priority again

**Pull request closed without merging**
